version: '2'
services:
  moodle:
    image: docker.io/bitnami/moodle:latest
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_TYPE=mysqli
      - MOODLE_DATABASE_HOST=moodle-db.cdwk017yeslt.us-east-1.rds.amazonaws.com
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=admin
      - MOODLE_DATABASE_NAME=bd_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MOODLE_DATABASE_PASSWORD=moodle1234
      - BITNAMI_DEBUG=true
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
volumes:
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
